const PatientRegisterSchema = {
  type: 'object',
  properties: {
    nome: { type: 'string', maxLength: 255 },
    email: { type: 'string', maxLength: 100, format: 'email' },
    dataNascimento: { type: 'string', maxLength: 100, format: 'date' },
    altura: { type: 'number', format: 'float' },
    peso: { type: 'number', format: 'float' },
    senha: { type: 'string', maxLength: 100 },
    confirmar_senha: { type: 'string', maxLength: 100 },
    objetivo: { type: 'string', maxLength: 255 },
    nutricionista_id: { type: 'integer' },
    genero: { type: 'string', enum: ['M', 'F'] },
    telefone: { type: 'string', maxLength: 20 },
    observacao: { type: 'string', format: 'textarea' },
    historico_familiar_doencas: { type: 'string', format: 'textarea' },
    doencas_cronicas: { type: 'string', format: 'textarea' },
    medicamentos_em_uso: { type: 'string', format: 'textarea' },
    exames_de_sangue_relevantes: { type: 'string', format: 'textarea' },
    alergia: { type: 'string', format: 'textarea' },
    restricao_alimentar: { type: 'string', format: 'textarea' },
    habitos_alimentares: { type: 'string', format: 'textarea' },
    frequencia_exercicio_semanal: { type: 'string', maxLength: 45 },
    circunferencia_bracos: { type: 'number', format: 'float' },
    circunferencia_cintura: { type: 'number', format: 'float' },
    circunferencia_quadril: { type: 'number', format: 'float' },
    circunferencia_pernas: { type: 'number', format: 'float' },
  },
  required: [
    'nome',
    'email',
    'senha',
    'confirmarSenha',
    'dataNascimento',
    'altura',
    'peso',
    'confirmar_senha',
    'nutricionista_id ',
  ],
};

export default PatientRegisterSchema;
